SELECT TO_CHAR(SALE.SALES_DATE, 'YYYY') YEAR,
TO_NUMBER(TO_CHAR(SALE.SALES_DATE, 'MM')) MONTH,
INFO.GENDER GENDER,
COUNT(DISTINCT INFO.USER_ID) USERS
FROM USER_INFO INFO JOIN ONLINE_SALE SALE
ON INFO.USER_ID = SALE.USER_ID
GROUP BY TO_CHAR(SALE.SALES_DATE, 'YYYY'),
TO_NUMBER(TO_CHAR(SALE.SALES_DATE, 'MM')),
INFO.GENDER
HAVING INFO.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;
