SELECT TIME.HOUR AS HOUR, COUNT(OUTS.DTIME) AS COUNT
FROM 
(SELECT LEVEL-1 AS HOUR
 FROM DUAL
 CONNECT BY LEVEL<=24) TIME
 LEFT JOIN 
 (SELECT TO_CHAR(DATETIME, 'HH24') AS DTIME
 FROM ANIMAL_OUTS) OUTS
 ON TIME.HOUR = OUTS.DTIME
 GROUP BY TIME.HOUR
 ORDER BY TIME.HOUR;
