SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, TO_CHAR(REV.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE PRO JOIN REST_REVIEW REV
ON PRO.MEMBER_ID = REV.MEMBER_ID
WHERE PRO.MEMBER_ID = (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(REVIEW_ID) DESC
FETCH FIRST 1 ROWS ONLY)
ORDER BY REV.REVIEW_DATE ASC, REV.REVIEW_TEXT;
