SELECT BOA.TITLE, BOA.BOARD_ID, REP.REPLY_ID, REP.WRITER_ID, REP.CONTENTS, TO_CHAR(REP.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD BOA JOIN USED_GOODS_REPLY REP
ON BOA.BOARD_ID = REP.BOARD_ID
WHERE TO_CHAR(BOA.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY REP.CREATED_DATE ASC, BOA.TITLE;
